"""
Compiled Artifact Models - Phase 2
These models store the compiled artifacts generated by the Blueprint Compiler.
They represent the internal artifacts that the evaluation pipeline consumes.
"""

from sqlalchemy import Column, String, DateTime, ForeignKey, Boolean, Integer, Text, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from app.database import Base
from datetime import datetime
import uuid
import enum


class CompiledFlowVersion(Base):
    """Compiled FlowVersion artifact"""
    __tablename__ = "compiled_flow_versions"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    company_id = Column(String(36), ForeignKey("companies.id"), nullable=False, index=True)
    blueprint_version_id = Column(String(36), nullable=True, index=True)  # Link to qa_blueprint_versions
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False, index=True)
    version_number = Column(Integer, nullable=False, default=1)
    language = Column(String(10), nullable=True)  # From blueprint metadata
    extra_metadata = Column(JSONB, nullable=True, name="metadata")  # Policy metadata, retention flags, etc.
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    company = relationship("Company")
    stages = relationship("CompiledFlowStage", back_populates="flow_version", cascade="all, delete-orphan", order_by="CompiledFlowStage.ordering_index")
    compliance_rules = relationship("CompiledComplianceRule", back_populates="flow_version", cascade="all, delete-orphan")
    rubric_templates = relationship("CompiledRubricTemplate", back_populates="flow_version", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<CompiledFlowVersion(id='{self.id}', name='{self.name}', version={self.version_number})>"


class CompiledFlowStage(Base):
    """Compiled FlowStage artifact"""
    __tablename__ = "compiled_flow_stages"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    flow_version_id = Column(String(36), ForeignKey("compiled_flow_versions.id", ondelete="CASCADE"), nullable=False, index=True)
    name = Column(String(255), nullable=False)
    ordering_index = Column(Integer, nullable=False)
    stage_weight = Column(JSONB, nullable=True)  # Stage weight from blueprint
    expected_duration_hint = Column(Integer, nullable=True)  # From metadata
    extra_metadata = Column(JSONB, nullable=True, name="metadata")  # ui_label, color, sample_window_seconds
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    flow_version = relationship("CompiledFlowVersion", back_populates="stages")
    steps = relationship("CompiledFlowStep", back_populates="stage", cascade="all, delete-orphan", order_by="CompiledFlowStep.ordering_index")
    
    def __repr__(self):
        return f"<CompiledFlowStage(id='{self.id}', name='{self.name}', ordering_index={self.ordering_index})>"


class CompiledFlowStep(Base):
    """Compiled FlowStep artifact"""
    __tablename__ = "compiled_flow_steps"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    stage_id = Column(String(36), ForeignKey("compiled_flow_stages.id", ondelete="CASCADE"), nullable=False, index=True)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    ordering_index = Column(Integer, nullable=False)
    expected_role = Column(String(50), default="agent", nullable=False)  # Usually "agent", can override from metadata
    expected_phrases = Column(JSONB, nullable=True)  # Array of strings (if detection_mode != semantic)
    detection_hint = Column(String(50), nullable=True)  # detection_mode from behavior
    extra_metadata = Column(JSONB, nullable=True, name="metadata")  # behavior_type, critical_action, examples, language_hint
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    stage = relationship("CompiledFlowStage", back_populates="steps")
    compliance_rules = relationship("CompiledComplianceRule", back_populates="flow_step", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<CompiledFlowStep(id='{self.id}', name='{self.name}', ordering_index={self.ordering_index})>"


class RuleType(str, enum.Enum):
    """Compliance rule types"""
    required_step = "required_step"
    required_phrase = "required_phrase"
    forbidden_phrase = "forbidden_phrase"
    timing_rule = "timing_rule"
    sequence_rule = "sequence_rule"


class Severity(str, enum.Enum):
    """Rule severity levels"""
    critical = "critical"
    major = "major"
    minor = "minor"


class CompiledComplianceRule(Base):
    """Compiled ComplianceRule artifact"""
    __tablename__ = "compiled_compliance_rules"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    flow_version_id = Column(String(36), ForeignKey("compiled_flow_versions.id", ondelete="CASCADE"), nullable=False, index=True)
    flow_step_id = Column(String(36), ForeignKey("compiled_flow_steps.id", ondelete="CASCADE"), nullable=True, index=True)
    rule_type = Column(SQLEnum(RuleType), nullable=False)
    target = Column(String(36), nullable=True)  # FlowStep ID
    phrases = Column(JSONB, nullable=True)  # expected_phrases (if any)
    match_mode = Column(String(50), nullable=True)  # semantic | exact | hybrid
    severity = Column(SQLEnum(Severity), nullable=False, default=Severity.major)
    action_on_fail = Column(String(50), nullable=True)  # critical_action (fail_stage/fail_overall/flag)
    timing_constraints = Column(JSONB, nullable=True)  # Numeric constraint fields if provided
    active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    flow_version = relationship("CompiledFlowVersion", back_populates="compliance_rules")
    flow_step = relationship("CompiledFlowStep", back_populates="compliance_rules")
    
    def __repr__(self):
        return f"<CompiledComplianceRule(id='{self.id}', rule_type={self.rule_type.value}, severity={self.severity.value})>"


class CompiledRubricTemplate(Base):
    """Compiled RubricTemplate artifact"""
    __tablename__ = "compiled_rubric_templates"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    flow_version_id = Column(String(36), ForeignKey("compiled_flow_versions.id", ondelete="CASCADE"), nullable=False, index=True)
    name = Column(String(255), nullable=False)
    categories = Column(JSONB, nullable=False)  # [{id, name, weight}] - stages as categories
    mappings = Column(JSONB, nullable=False)  # [{category_id, flow_step_id, contribution_weight}]
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    flow_version = relationship("CompiledFlowVersion", back_populates="rubric_templates")
    
    def __repr__(self):
        return f"<CompiledRubricTemplate(id='{self.id}', name='{self.name}')>"

