"""
Phase 2: Policy Rule Builder - Policy Rules Version Model
Stores versioned snapshots of finalized policy rules.
"""

from sqlalchemy import Column, String, DateTime, ForeignKey, Integer, Text, Boolean
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from app.database import Base
from datetime import datetime
import uuid


class PolicyRulesVersion(Base):
    __tablename__ = "policy_rules_versions"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    policy_template_id = Column(String(36), ForeignKey("policy_templates.id"), nullable=False)
    rules_version = Column(Integer, nullable=False)  # Incremental version number per template

    # The finalized policy rules
    policy_rules = Column(JSONB, nullable=False)

    # Source tracking
    draft_id = Column(String(36), ForeignKey("policy_rules_drafts.id"), nullable=True)

    # LLM metadata for reproducibility
    llm_model = Column(String(100), nullable=True)
    llm_prompt_hash = Column(String(64), nullable=True)  # SHA-256 hash of prompt template used

    # Phase 5: Rule Editor UI enhancements
    name = Column(String(100), nullable=True)            # Version name/label
    notes = Column(Text, nullable=True)                  # Version notes/changelog
    llm_generated = Column(Boolean, nullable=False, default=True)  # True if generated by LLM
    rules_hash = Column(String(64), nullable=True)       # SHA256 hash of rules JSON
    diff_from_previous = Column(JSONB, nullable=True)    # JSON diff from previous version

    # Audit fields
    created_by_user_id = Column(String(36), ForeignKey("users.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    policy_template = relationship("PolicyTemplate", back_populates="policy_rules_versions")
    draft = relationship("PolicyRulesDraft")
    created_by_user = relationship("User", foreign_keys=[created_by_user_id])

    def __repr__(self):
        return f"<PolicyRulesVersion(id='{self.id}', template_id='{self.policy_template_id}', version={self.rules_version})>"
