
"""phase1_agent_team_directory

Revision ID: 0123456789ab
Revises: 1015163832c8
Create Date: 2025-11-10 14:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0123456789ab'
down_revision = '1015163832c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create teams table
    op.create_table('teams',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('company_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=36), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_teams_company_id_companies'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_teams_created_by_users'),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_teams_updated_by_users'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('company_id', 'name', name='uq_teams_company_id_name')
    )
    op.create_index(op.f('ix_teams_company_id'), 'teams', ['company_id'], unique=False)

    # Create agent_team_memberships table
    op.create_table('agent_team_memberships',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('agent_id', sa.String(length=36), nullable=False),
        sa.Column('team_id', sa.String(length=36), nullable=False),
        sa.Column('role', sa.String(length=50), server_default='agent', nullable=True),
        sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name='fk_agent_team_memberships_agent_id_users'),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_agent_team_memberships_team_id_teams'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_agent_team_memberships_created_by_users'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('agent_id', 'team_id', name='uq_agent_team_memberships_agent_id_team_id')
    )
    op.create_index(op.f('ix_agent_team_memberships_agent_id'), 'agent_team_memberships', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_team_memberships_team_id'), 'agent_team_memberships', ['team_id'], unique=False)

    # Create agent_team_changes table
    op.create_table('agent_team_changes',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.String(length=36), nullable=False),
        sa.Column('change_type', sa.String(length=50), nullable=False),
        sa.Column('field_name', sa.String(length=255), nullable=True),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('changed_by', sa.String(length=36), nullable=False),
        sa.Column('changed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('company_id', sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='fk_agent_team_changes_changed_by_users'),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_agent_team_changes_company_id_companies'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_team_changes_company_id_changed_at'), 'agent_team_changes', ['company_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_agent_team_changes_entity_id_changed_at'), 'agent_team_changes', ['entity_id', 'changed_at'], unique=False)

    # Create import_jobs table
    op.create_table('import_jobs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('company_id', sa.String(length=36), nullable=False),
        sa.Column('source_type', sa.String(length=50), nullable=False),
        sa.Column('source_platform', sa.String(length=50), server_default='n/a', nullable=True),
        sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=True),
        sa.Column('rows_total', sa.Integer(), nullable=True),
        sa.Column('rows_processed', sa.Integer(), server_default='0', nullable=True),
        sa.Column('rows_failed', sa.Integer(), server_default='0', nullable=True),
        sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_import_jobs_company_id_companies'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_import_jobs_created_by_users'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_company_id_created_at'), 'import_jobs', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)

    # Modifications to 'users' table
    op.add_column('users', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key('fk_users_created_by_users', 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_users_updated_by_users', 'users', 'users', ['updated_by'], ['id'])

    # Modifications to 'recordings' table
    op.add_column('recordings', sa.Column('agent_id', sa.String(length=36), nullable=True))
    op.add_column('recordings', sa.Column('team_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_recordings_agent_id_users', 'recordings', 'users', ['agent_id'], ['id'])
    op.create_foreign_key('fk_recordings_team_id_teams', 'recordings', 'teams', ['team_id'], ['id'])
    op.create_index(op.f('ix_recordings_agent_id'), 'recordings', ['agent_id'], unique=False)

    # Modifications to 'evaluations' table
    op.add_column('evaluations', sa.Column('agent_id', sa.String(length=36), nullable=True))
    op.add_column('evaluations', sa.Column('team_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_evaluations_agent_id_users', 'evaluations', 'users', ['agent_id'], ['id'])
    op.create_foreign_key('fk_evaluations_team_id_teams', 'evaluations', 'teams', ['team_id'], ['id'])
    op.create_index(op.f('ix_evaluations_agent_id'), 'evaluations', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrade for 'evaluations' table
    op.drop_index(op.f('ix_evaluations_agent_id'), table_name='evaluations')
    op.drop_constraint('fk_evaluations_team_id_teams', 'evaluations', type_='foreignkey')
    op.drop_constraint('fk_evaluations_agent_id_users', 'evaluations', type_='foreignkey')
    op.drop_column('evaluations', 'team_id')
    op.drop_column('evaluations', 'agent_id')

    # Downgrade for 'recordings' table
    op.drop_index(op.f('ix_recordings_agent_id'), table_name='recordings')
    op.drop_constraint('fk_recordings_team_id_teams', 'recordings', type_='foreignkey')
    op.drop_constraint('fk_recordings_agent_id_users', 'recordings', type_='foreignkey')
    op.drop_column('recordings', 'team_id')
    op.drop_column('recordings', 'agent_id')

    # Downgrade for 'users' table
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')

    # Drop tables in reverse order of creation
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_company_id_created_at'), table_name='import_jobs')
    op.drop_table('import_jobs')

    op.drop_index(op.f('ix_agent_team_changes_entity_id_changed_at'), table_name='agent_team_changes')
    op.drop_index(op.f('ix_agent_team_changes_company_id_changed_at'), table_name='agent_team_changes')
    op.drop_table('agent_team_changes')

    op.drop_index(op.f('ix_agent_team_memberships_team_id'), table_name='agent_team_memberships')
    op.drop_index(op.f('ix_agent_team_memberships_agent_id'), table_name='agent_team_memberships')
    op.drop_constraint('uq_agent_team_memberships_agent_id_team_id', 'agent_team_memberships', type_='unique')
    op.drop_constraint('fk_agent_team_memberships_team_id_teams', 'agent_team_memberships', type_='foreignkey')
    op.drop_constraint('fk_agent_team_memberships_agent_id_users', 'agent_team_memberships', type_='foreignkey')
    op.drop_table('agent_team_memberships')

    op.drop_index(op.f('ix_teams_company_id'), table_name='teams')
    op.drop_constraint('uq_teams_company_id_name', 'teams', type_='unique')
    op.drop_table('teams')
    # ### end Alembic commands ###
