"""add_sentiment_analysis_to_transcript

Revision ID: cca6c2c11b1a
Revises: 50355ee2454a
Create Date: 2025-11-09 01:59:40.940332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cca6c2c11b1a'
down_revision = '50355ee2454a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('evaluation_criteria', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_evaluation_rubric_levels_criteria_id', table_name='evaluation_rubric_levels')
    op.alter_column('evaluations', 'status',
               existing_type=postgresql.ENUM('pending', 'completed', 'reviewed', name='evaluationstatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::evaluationstatus"))
    op.alter_column('evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('evaluations_recording_id_key', 'evaluations', type_='unique')
    op.drop_index('ix_evaluations_recording_id', table_name='evaluations')
    op.create_index(op.f('ix_evaluations_recording_id'), 'evaluations', ['recording_id'], unique=True)
    op.alter_column('policy_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('policy_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('recordings', 'status',
               existing_type=postgresql.ENUM('queued', 'processing', 'completed', 'failed', name='recordingstatus'),
               nullable=True,
               existing_server_default=sa.text("'queued'::recordingstatus"))
    op.alter_column('recordings', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('transcripts', sa.Column('sentiment_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('transcripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'qa_manager', 'reviewer', name='userrole'),
               nullable=True,
               existing_server_default=sa.text("'reviewer'::userrole"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'qa_manager', 'reviewer', name='userrole'),
               nullable=False,
               existing_server_default=sa.text("'reviewer'::userrole"))
    op.alter_column('transcripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('transcripts', 'sentiment_analysis')
    op.alter_column('recordings', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('recordings', 'status',
               existing_type=postgresql.ENUM('queued', 'processing', 'completed', 'failed', name='recordingstatus'),
               nullable=False,
               existing_server_default=sa.text("'queued'::recordingstatus"))
    op.alter_column('policy_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('policy_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_evaluations_recording_id'), table_name='evaluations')
    op.create_index('ix_evaluations_recording_id', 'evaluations', ['recording_id'], unique=False)
    op.create_unique_constraint('evaluations_recording_id_key', 'evaluations', ['recording_id'])
    op.alter_column('evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('evaluations', 'status',
               existing_type=postgresql.ENUM('pending', 'completed', 'reviewed', name='evaluationstatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::evaluationstatus"))
    op.create_index('ix_evaluation_rubric_levels_criteria_id', 'evaluation_rubric_levels', ['criteria_id'], unique=False)
    op.alter_column('evaluation_criteria', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###

